(function($){"use strict";function handlePreloader(){if($('.preloader').length){$('.preloader').delay(200).fadeOut(500);}}
function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-to-top');var sticky_header=$('.main-header .sticky-header');if(windowpos>100){siteHeader.addClass('fixed-header');sticky_header.addClass("animated slideInDown");scrollLink.fadeIn(300);}else{siteHeader.removeClass('fixed-header');sticky_header.removeClass("animated slideInDown");scrollLink.fadeOut(300);}}}
headerStyle();if($('.main-header li.menu-item-has-children  ul').length){$('.main-header .navigation li.menu-item-has-children ').append('<div class="dropdown-btn"><span class="fa fa-angle-right"></span></div>');}
if($('.mobile-menu').length){$('.mobile-menu .menu-box').mCustomScrollbar();var mobileMenuContent=$('.main-header .nav-outer .main-menu .navigation').html();$('.mobile-menu .navigation').append(mobileMenuContent);$('.sticky-header .navigation').append(mobileMenuContent);$('.mobile-menu .close-btn').on('click',function(){$('body').removeClass('mobile-menu-visible');});$('.mobile-menu li.menu-item-has-children .dropdown-btn').on('click',function(){$(this).toggleClass('open');$(this).prev('ul').slideToggle(500);});$('.mobile-nav-toggler').on('click',function(){$('body').addClass('mobile-menu-visible');});$('.mobile-menu .menu-backdrop,.mobile-menu .close-btn').on('click',function(){$('body').removeClass('mobile-menu-visible');});}
if($('.tabs-box').length){$('.tabs-box .tab-buttons .tab-btn').on('click',function(e){e.preventDefault();var target=$($(this).attr('data-tab'));if($(target).is(':visible')){return false;}else{target.parents('.tabs-box').find('.tab-buttons').find('.tab-btn').removeClass('active-btn');$(this).addClass('active-btn');target.parents('.tabs-box').find('.tabs-content').find('.tab').fadeOut(0);target.parents('.tabs-box').find('.tabs-content').find('.tab').removeClass('active-tab animated fadeIn');$(target).fadeIn(300);$(target).addClass('active-tab animated fadeIn');}});}
if($('.count-box').length){$('.count-box').appear(function(){var $t=$(this),n=$t.find(".count-text").attr("data-stop"),r=parseInt($t.find(".count-text").attr("data-speed"),10);if(!$t.hasClass("counted")){$t.addClass("counted");$({countNum:$t.find(".count-text").text()}).animate({countNum:n},{duration:r,easing:"linear",step:function(){$t.find(".count-text").text(Math.floor(this.countNum));},complete:function(){$t.find(".count-text").text(this.countNum);}});}},{accY:0});}
if($('.filter-list').length){$('.filter-list').mixItUp({});}
if($('.lightbox-image').length){$('.lightbox-image').fancybox({openEffect:'fade',closeEffect:'fade',helpers:{media:{}}});}
if($('.default-accordion-box').length){$(".default-accordion-box").on('click','.acc-btn',function(){var outerBox=$(this).parents('.default-accordion-box');var target=$(this).parents('.accordion');if($(this).hasClass('active')!==true){$(outerBox).find('.accordion .acc-btn').removeClass('active');}
if($(this).next('.acc-content').is(':visible')){return false;}else{$(this).addClass('active');$(outerBox).children('.accordion').removeClass('active-block');$(outerBox).find('.accordion').children('.acc-content').slideUp(300);target.addClass('active-block');$(this).next('.acc-content').slideDown(300);}});}
if($('.near-by-clicker').length){$(".near-by-clicker").on('click','.acc-btn',function(){$('.place-holder').removeClass('active');var outerBox=$(this).parents('.near-by-clicker');var target=$(this).parents('.accordion');if($(this).hasClass('active')!==true){$(outerBox).find('.accordion .acc-btn').removeClass('active');}
if($(this).next('.acc-content').is(':visible')){return false;}else{$(this).addClass('active');$(outerBox).children('.accordion').removeClass('active-block');$(outerBox).find('.accordion').children('.acc-content').slideUp(300);target.addClass('active-block');$(this).next('.acc-content').slideDown(300);}});$(".neighbour-section .place-outer .place-holder .place-mark").on('click',function(){var outerBox=$(this).parents('.neighbour-section');var targetBox=$(this).attr('data-clicker');var target=$(targetBox).find('.acc-content');var targetBtn=$(targetBox).find('.acc-btn');var targetPop=$(this).parent('.place-holder');if($(target).is(':visible')){$(targetPop).addClass('active');return false;}else{$(outerBox).find('.place-holder').removeClass('active');$(targetPop).addClass('active');$(outerBox).find('.accordion .acc-btn').removeClass('active');$(targetBtn).addClass('active');$(outerBox).find('.accordion').removeClass('active-block');$(outerBox).find('.accordion').children('.acc-content').slideUp(300);$(targetBox).addClass('active-block');$(target).slideDown(300);}});}
if($('.near-by-clicker').length){$('.near-by-clicker').mCustomScrollbar();}
if($('.scroll-to-target').length){$(".scroll-to-target").on('click',function(){var target=$(this).attr('data-target');$('html, body').animate({scrollTop:$(target).offset().top},1500);});}
if($('.wow').length){var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true});wow.init();}
if($('.filter-list').length){$('.filter-list').mixItUp({});}
$(window).on('scroll',function(){headerStyle();});$(window).on('load',function(){handlePreloader();});jQuery(document).on('ready',function(){jQuery(".image_background").each(function(){var attr=$(this).attr('data-image-src');if(typeof attr!==typeof undefined&&attr!==false){$(this).css('background-image','url('+attr+')');}});});})(window.jQuery);